# Generated by Django 5.1.7 on 2025-03-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
