
services:
  db:
    image: postgres:17  # ✅ 使用較新的 PostgreSQL 版本
    restart: always
    env_file:
      - .env  # ✅ 使用 .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # ✅ 確保 PostgreSQL 準備好
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 sonic_vision.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # ✅ 等待 PostgreSQL 準備好
    env_file:
      - .env  # ✅ 讀取環境變數
    restart: always  # ✅ 確保 Django 重新啟動

volumes:
  postgres_data: