version: "3.8"

services:
  db:
    image: postgres:17  # ✅ 使用較新的 PostgreSQL 版本
    restart: unless-stopped  # ✅ 避免無限重啟
    env_file:
      - .env  # ✅ 使用 .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # ✅ 確保 PostgreSQL 準備好
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "sonic_vision.wsgi:application"]  # ✅ 精簡 command
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # ✅ 等待 PostgreSQL 準備好
    env_file:
      - .env  # ✅ 讀取環境變數
    restart: unless-stopped  # ✅ 避免無限重啟
    healthcheck:  # ✅ 確保 Gunicorn 啟動成功
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: