version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env  # ✅ 讀取環境變數
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # ✅ 讓 Django 也讀取 .env

volumes:
  postgres_data: