# Generated by Django 5.1.6 on 2025-03-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('tmdb_url', models.URLField(blank=True, max_length=500, null=True)),
                ('poster_image', models.URLField(blank=True, max_length=500, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
